### ISSUE TITLE
[10.0] Account Payment Widget Amount module traceback

### ISSUE THREAD

**Issue by bharatrdevnani** [OCA/account-payment#280] opened 2019-08-08 05:38 UTC
I have installed the module, and when I go to any open invoices which has payment registered against that partner. System throws following trace back:

Error: QWeb2: Template 'PaymentAmountPopOver' not found
http://0.0.0.0:8069/web/content/252-6cdd5c8/web.assets_common.js:2908
Traceback:
exception@http://0.0.0.0:8069/web/content/252-6cdd5c8/web.assets_common.js:2908:7
_render@http://0.0.0.0:8069/web/content/252-6cdd5c8/web.assets_common.js:2953:103
render@http://0.0.0.0:8069/web/content/252-6cdd5c8/web.assets_common.js:2949:151
render_value/<@http://0.0.0.0:8069/web/content/6368-a124525/web.assets_backend.js:2803:850
_.forEach@http://0.0.0.0:8069/web/content/252-6cdd5c8/web.assets_common.js:12:558
render_value@http://0.0.0.0:8069/web/content/6368-a124525/web.assets_backend.js:2803:766
start/<@http://0.0.0.0:8069/web/content/6368-a124525/web.assets_backend.js:2231:314
trigger@http://0.0.0.0:8069/web/content/252-6cdd5c8/web.assets_common.js:3105:180
trigger@http://0.0.0.0:8069/web/content/252-6cdd5c8/web.assets_common.js:3109:148
set/<@http://0.0.0.0:8069/web/content/252-6cdd5c8/web.assets_common.js:3113:6
_.forEach@http://0.0.0.0:8069/web/content/252-6cdd5c8/web.assets_common.js:12:650
set@http://0.0.0.0:8069/web/content/252-6cdd5c8/web.assets_common.js:3110:35
set_value@http://0.0.0.0:8069/web/content/6368-a124525/web.assets_backend.js:2232:637
set_value_from_record@http://0.0.0.0:8069/web/content/6368-a124525/web.assets_backend.js:2232:715
load_record/<@http://0.0.0.0:8069/web/content/6368-a124525/web.assets_backend.js:2135:170
_.forEach@http://0.0.0.0:8069/web/content/252-6cdd5c8/web.assets_common.js:12:650
_.mixin/</_.prototype[name]@http://0.0.0.0:8069/web/content/252-6cdd5c8/web.assets_common.js:69:526
load_record@http://0.0.0.0:8069/web/content/6368-a124525/web.assets_backend.js:2135:71
trigger@http://0.0.0.0:8069/web/content/252-6cdd5c8/web.assets_common.js:3105:180
trigger@http://0.0.0.0:8069/web/content/252-6cdd5c8/web.assets_common.js:3109:148
do_show/shown</<@http://0.0.0.0:8069/web/content/6368-a124525/web.assets_backend.js:2133:190
then/</</<@http://0.0.0.0:8069/web/content/252-6cdd5c8/web.assets_common.js:547:681
fire@http://0.0.0.0:8069/web/content/252-6cdd5c8/web.assets_common.js:541:299
fireWith@http://0.0.0.0:8069/web/content/252-6cdd5c8/web.assets_common.js:546:198
then/</</<@http://0.0.0.0:8069/web/content/252-6cdd5c8/web.assets_common.js:547:874
fire@http://0.0.0.0:8069/web/content/252-6cdd5c8/web.assets_common.js:541:299
fireWith@http://0.0.0.0:8069/web/content/252-6cdd5c8/web.assets_common.js:546:198
then/</</<@http://0.0.0.0:8069/web/content/252-6cdd5c8/web.assets_common.js:547:874
fire@http://0.0.0.0:8069/web/content/252-6cdd5c8/web.assets_common.js:541:299
fireWith@http://0.0.0.0:8069/web/content/252-6cdd5c8/web.assets_common.js:546:198
Deferred/</deferred[tuple[0]]@http://0.0.0.0:8069/web/content/252-6cdd5c8/web.assets_common.js:548:56
fire@http://0.0.0.0:8069/web/content/252-6cdd5c8/web.assets_common.js:541:299
fireWith@http://0.0.0.0:8069/web/content/252-6cdd5c8/web.assets_common.js:546:198
then/</</<@http://0.0.0.0:8069/web/content/252-6cdd5c8/web.assets_common.js:547:874
fire@http://0.0.0.0:8069/web/content/252-6cdd5c8/web.assets_common.js:541:299
fireWith@http://0.0.0.0:8069/web/content/252-6cdd5c8/web.assets_common.js:546:198
then/</</<@http://0.0.0.0:8069/web/content/252-6cdd5c8/web.assets_common.js:547:874
fire@http://0.0.0.0:8069/web/content/252-6cdd5c8/web.assets_common.js:541:299
fireWith@http://0.0.0.0:8069/web/content/252-6cdd5c8/web.assets_common.js:546:198
done@http://0.0.0.0:8069/web/content/252-6cdd5c8/web.assets_common.js:937:95
callback@http://0.0.0.0:8069/web/content/252-6cdd5c8/web.assets_common.js:957:15

**Comment by pedrobaeza** [comment] 2019-08-08 07:24
Hi, thanks for reporting. Are you able to reproduce the problem in runbot infrastructure (https://runbot.odoo-community.org/runbot/repo/github-com-oca-account-payment-96 - admin/admin)?

If so, please explain with all the possible detailed steps to get to the error. Not having them, it's very difficult to hunt down the problem. Please don't be shy of adding details, and even better if you provide some screenshots or videos.

If not, this can be due to a configuration change, a custom/community module you have deployed in your DB or an outdated code. Please report back if it's the case.

For keeping a clean house in this issue tracker, if you don't answer in several days, this will be closed assuming it was one of the stated things.

**Comment by bharatrdevnani** [comment] 2019-08-08 13:06
Hi,

Thanks for your swift response, I have tried on runbot and in local both works perfectly alright, but i don't know why its appearing in my production server. 

Any pointers will be much appreciated!

**Comment by pedrobaeza** [comment] 2019-08-08 13:42
Possible reasons:

* Outdated code
* Other modules that conflict with this one
* DB instance without updated modules. Upgrade `base` module or put `-u all` launching the service.

Closing this then as no regular issue, but deployment problem.

**Closed as completed by pedrobaeza** 2019-08-08 13:42 UTC

**Comment by farazbdm** [comment] 2020-10-27 13:03
@pedrobaeza 
this case can be recreated on runbot as well,
when there are multiple lines of Accounts Receivable the iterations of paid_amt considers full amount for each line to match.
that causes the issue.

i will make PR

**Comment by pedrobaeza** [comment] 2020-10-27 13:05
OK then. Waiting for PR, but FYI I'm not a user of this module, and not even working with this old version, but only handling OCA issues.

**Comment by farazbdm** [comment] 2020-10-27 13:08
sorry my bad, mentioned on wrong issue, i meant to mention another issue. Apologies again
